language: python
sudo: false
dist: trusty
python:
  - 2.7

env:
  - DJANGO=1.10.5

before_install:
  - export DJANGO_SETTINGS_MODULE=workbench-backend/workbench/settings.py
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements
  - npm install workbench-frontend/package.json

script:
  - python workbench-backend/manage.py test