language: python
sudo: false
dist: trusty
python:
  - 2.7

env:
  - DJANGO=1.10.5

before_install:
  - export PIP_USE_MIRRORS=true

install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda env create --file env.yml
  - source activate workbench
  - cd workbench-backend
#  - npm install workbench-frontend/package.json

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test